// Copyright (c) 2005-2020 Code Synthesis Tools CC.
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

// Begin prologue.
//
//
// End prologue.

#include <xsde/cxx/pre.hxx>

#include "person-pskel.hxx"

namespace fhir
{
  // Person_pskel
  //

  void Person_pskel::
  identifier_parser (::fhir::Identifier_pskel& p)
  {
    this->identifier_parser_ = &p;
  }

  void Person_pskel::
  name_parser (::fhir::HumanName_pskel& p)
  {
    this->name_parser_ = &p;
  }

  void Person_pskel::
  telecom_parser (::fhir::ContactPoint_pskel& p)
  {
    this->telecom_parser_ = &p;
  }

  void Person_pskel::
  gender_parser (::fhir::AdministrativeGender_pskel& p)
  {
    this->gender_parser_ = &p;
  }

  void Person_pskel::
  birthDate_parser (::fhir::date_pskel& p)
  {
    this->birthDate_parser_ = &p;
  }

  void Person_pskel::
  address_parser (::fhir::Address_pskel& p)
  {
    this->address_parser_ = &p;
  }

  void Person_pskel::
  photo_parser (::fhir::Attachment_pskel& p)
  {
    this->photo_parser_ = &p;
  }

  void Person_pskel::
  managingOrganization_parser (::fhir::Reference_pskel& p)
  {
    this->managingOrganization_parser_ = &p;
  }

  void Person_pskel::
  active_parser (::fhir::boolean_pskel& p)
  {
    this->active_parser_ = &p;
  }

  void Person_pskel::
  link_parser (::fhir::Person_Link_pskel& p)
  {
    this->link_parser_ = &p;
  }

  void Person_pskel::
  parsers (::fhir::id_pskel& id,
           ::fhir::Meta_pskel& meta,
           ::fhir::uri_pskel& implicitRules,
           ::fhir::code_pskel& language,
           ::fhir::Narrative_pskel& text,
           ::fhir::ResourceContainer_pskel& contained,
           ::fhir::Extension_pskel& extension,
           ::fhir::Extension_pskel& modifierExtension,
           ::fhir::Identifier_pskel& identifier,
           ::fhir::HumanName_pskel& name,
           ::fhir::ContactPoint_pskel& telecom,
           ::fhir::AdministrativeGender_pskel& gender,
           ::fhir::date_pskel& birthDate,
           ::fhir::Address_pskel& address,
           ::fhir::Attachment_pskel& photo,
           ::fhir::Reference_pskel& managingOrganization,
           ::fhir::boolean_pskel& active,
           ::fhir::Person_Link_pskel& link)
  {
    this->id_parser_ = &id;
    this->meta_parser_ = &meta;
    this->implicitRules_parser_ = &implicitRules;
    this->language_parser_ = &language;
    this->text_parser_ = &text;
    this->contained_parser_ = &contained;
    this->extension_parser_ = &extension;
    this->modifierExtension_parser_ = &modifierExtension;
    this->identifier_parser_ = &identifier;
    this->name_parser_ = &name;
    this->telecom_parser_ = &telecom;
    this->gender_parser_ = &gender;
    this->birthDate_parser_ = &birthDate;
    this->address_parser_ = &address;
    this->photo_parser_ = &photo;
    this->managingOrganization_parser_ = &managingOrganization;
    this->active_parser_ = &active;
    this->link_parser_ = &link;
  }

  Person_pskel::
  Person_pskel (::fhir::DomainResource_pskel* tiein)
  : ::fhir::DomainResource_pskel (tiein, 0),
    Person_impl_ (0),
    identifier_parser_ (0),
    name_parser_ (0),
    telecom_parser_ (0),
    gender_parser_ (0),
    birthDate_parser_ (0),
    address_parser_ (0),
    photo_parser_ (0),
    managingOrganization_parser_ (0),
    active_parser_ (0),
    link_parser_ (0),
    v_state_stack_ (sizeof (v_state_), &v_state_first_)
  {
  }

  Person_pskel::
  Person_pskel (Person_pskel* impl, void*)
  : ::fhir::DomainResource_pskel (impl, 0),
    Person_impl_ (impl),
    identifier_parser_ (0),
    name_parser_ (0),
    telecom_parser_ (0),
    gender_parser_ (0),
    birthDate_parser_ (0),
    address_parser_ (0),
    photo_parser_ (0),
    managingOrganization_parser_ (0),
    active_parser_ (0),
    link_parser_ (0),
    v_state_stack_ (sizeof (v_state_), &v_state_first_)
  {
  }

  // Person_Link_pskel
  //

  void Person_Link_pskel::
  target_parser (::fhir::Reference_pskel& p)
  {
    this->target_parser_ = &p;
  }

  void Person_Link_pskel::
  assurance_parser (::fhir::IdentityAssuranceLevel_pskel& p)
  {
    this->assurance_parser_ = &p;
  }

  void Person_Link_pskel::
  parsers (::fhir::string_primitive_pskel& id,
           ::fhir::Extension_pskel& extension,
           ::fhir::Extension_pskel& modifierExtension,
           ::fhir::Reference_pskel& target,
           ::fhir::IdentityAssuranceLevel_pskel& assurance)
  {
    this->id_parser_ = &id;
    this->extension_parser_ = &extension;
    this->modifierExtension_parser_ = &modifierExtension;
    this->target_parser_ = &target;
    this->assurance_parser_ = &assurance;
  }

  Person_Link_pskel::
  Person_Link_pskel (::fhir::BackboneElement_pskel* tiein)
  : ::fhir::BackboneElement_pskel (tiein, 0),
    Person_Link_impl_ (0),
    target_parser_ (0),
    assurance_parser_ (0),
    v_state_stack_ (sizeof (v_state_), &v_state_first_)
  {
  }

  Person_Link_pskel::
  Person_Link_pskel (Person_Link_pskel* impl, void*)
  : ::fhir::BackboneElement_pskel (impl, 0),
    Person_Link_impl_ (impl),
    target_parser_ (0),
    assurance_parser_ (0),
    v_state_stack_ (sizeof (v_state_), &v_state_first_)
  {
  }

  // IdentityAssuranceLevel_list_pskel
  //

  IdentityAssuranceLevel_list_pskel::
  IdentityAssuranceLevel_list_pskel (::fhir::code_primitive_pskel* tiein)
  : ::fhir::code_primitive_pskel (tiein, 0),
    IdentityAssuranceLevel_list_impl_ (0)
  {
    this->_enumeration_facet (_xsde_IdentityAssuranceLevel_list_pskel_enums_, 4UL);
  }

  IdentityAssuranceLevel_list_pskel::
  IdentityAssuranceLevel_list_pskel (IdentityAssuranceLevel_list_pskel* impl, void*)
  : ::fhir::code_primitive_pskel (impl, 0),
    IdentityAssuranceLevel_list_impl_ (impl)
  {
    this->_enumeration_facet (_xsde_IdentityAssuranceLevel_list_pskel_enums_, 4UL);
  }

  // IdentityAssuranceLevel_pskel
  //

  void IdentityAssuranceLevel_pskel::
  value_parser (::fhir::IdentityAssuranceLevel_list_pskel& p)
  {
    this->value_parser_ = &p;
  }

  void IdentityAssuranceLevel_pskel::
  parsers (::fhir::string_primitive_pskel& id,
           ::fhir::Extension_pskel& extension,
           ::fhir::IdentityAssuranceLevel_list_pskel& value)
  {
    this->id_parser_ = &id;
    this->extension_parser_ = &extension;
    this->value_parser_ = &value;
  }

  IdentityAssuranceLevel_pskel::
  IdentityAssuranceLevel_pskel (::fhir::Element_pskel* tiein)
  : ::fhir::Element_pskel (tiein, 0),
    IdentityAssuranceLevel_impl_ (0),
    value_parser_ (0)
  {
  }

  IdentityAssuranceLevel_pskel::
  IdentityAssuranceLevel_pskel (IdentityAssuranceLevel_pskel* impl, void*)
  : ::fhir::Element_pskel (impl, 0),
    IdentityAssuranceLevel_impl_ (impl),
    value_parser_ (0)
  {
  }
}

#include <assert.h>

namespace fhir
{
  // Person_pskel
  //

  void Person_pskel::
  identifier ()
  {
    if (this->Person_impl_)
      this->Person_impl_->identifier ();
  }

  void Person_pskel::
  name ()
  {
    if (this->Person_impl_)
      this->Person_impl_->name ();
  }

  void Person_pskel::
  telecom ()
  {
    if (this->Person_impl_)
      this->Person_impl_->telecom ();
  }

  void Person_pskel::
  gender ()
  {
    if (this->Person_impl_)
      this->Person_impl_->gender ();
  }

  void Person_pskel::
  birthDate ()
  {
    if (this->Person_impl_)
      this->Person_impl_->birthDate ();
  }

  void Person_pskel::
  address ()
  {
    if (this->Person_impl_)
      this->Person_impl_->address ();
  }

  void Person_pskel::
  photo ()
  {
    if (this->Person_impl_)
      this->Person_impl_->photo ();
  }

  void Person_pskel::
  managingOrganization ()
  {
    if (this->Person_impl_)
      this->Person_impl_->managingOrganization ();
  }

  void Person_pskel::
  active ()
  {
    if (this->Person_impl_)
      this->Person_impl_->active ();
  }

  void Person_pskel::
  link ()
  {
    if (this->Person_impl_)
      this->Person_impl_->link ();
  }

  void Person_pskel::
  post_Person ()
  {
    if (this->Person_impl_)
      this->Person_impl_->post_Person ();
    else
      post_DomainResource ();
  }

  void Person_pskel::
  _reset ()
  {
    if (this->resetting_)
      return;

    typedef ::fhir::DomainResource_pskel base;
    base::_reset ();

    this->v_state_stack_.clear ();

    this->resetting_ = true;

    if (this->identifier_parser_)
      this->identifier_parser_->_reset ();

    if (this->name_parser_)
      this->name_parser_->_reset ();

    if (this->telecom_parser_)
      this->telecom_parser_->_reset ();

    if (this->gender_parser_)
      this->gender_parser_->_reset ();

    if (this->birthDate_parser_)
      this->birthDate_parser_->_reset ();

    if (this->address_parser_)
      this->address_parser_->_reset ();

    if (this->photo_parser_)
      this->photo_parser_->_reset ();

    if (this->managingOrganization_parser_)
      this->managingOrganization_parser_->_reset ();

    if (this->active_parser_)
      this->active_parser_->_reset ();

    if (this->link_parser_)
      this->link_parser_->_reset ();

    this->resetting_ = false;
  }

  // Person_Link_pskel
  //

  void Person_Link_pskel::
  target ()
  {
    if (this->Person_Link_impl_)
      this->Person_Link_impl_->target ();
  }

  void Person_Link_pskel::
  assurance ()
  {
    if (this->Person_Link_impl_)
      this->Person_Link_impl_->assurance ();
  }

  void Person_Link_pskel::
  post_Person_Link ()
  {
    if (this->Person_Link_impl_)
      this->Person_Link_impl_->post_Person_Link ();
    else
      post_BackboneElement ();
  }

  void Person_Link_pskel::
  _reset ()
  {
    if (this->resetting_)
      return;

    typedef ::fhir::BackboneElement_pskel base;
    base::_reset ();

    this->v_state_stack_.clear ();

    this->resetting_ = true;

    if (this->target_parser_)
      this->target_parser_->_reset ();

    if (this->assurance_parser_)
      this->assurance_parser_->_reset ();

    this->resetting_ = false;
  }

  // IdentityAssuranceLevel_list_pskel
  //

  void IdentityAssuranceLevel_list_pskel::
  post_IdentityAssuranceLevel_list ()
  {
    if (this->IdentityAssuranceLevel_list_impl_)
      this->IdentityAssuranceLevel_list_impl_->post_IdentityAssuranceLevel_list ();
    else
      post_code_primitive ();
  }

  const char* const IdentityAssuranceLevel_list_pskel::_xsde_IdentityAssuranceLevel_list_pskel_enums_[4UL] = 
  {
    "level1",
    "level2",
    "level3",
    "level4"
  };

  // IdentityAssuranceLevel_pskel
  //

  void IdentityAssuranceLevel_pskel::
  value ()
  {
    if (this->IdentityAssuranceLevel_impl_)
      this->IdentityAssuranceLevel_impl_->value ();
  }

  void IdentityAssuranceLevel_pskel::
  post_IdentityAssuranceLevel ()
  {
    if (this->IdentityAssuranceLevel_impl_)
      this->IdentityAssuranceLevel_impl_->post_IdentityAssuranceLevel ();
    else
      post_Element ();
  }

  void IdentityAssuranceLevel_pskel::
  _reset ()
  {
    typedef ::fhir::Element_pskel base;
    base::_reset ();

    if (this->value_parser_)
      this->value_parser_->_reset ();
  }
}

#include <assert.h>

namespace fhir
{
  // Element validation and dispatch functions for Person_pskel.
  //
  bool Person_pskel::
  _start_element_impl (const ::xsde::cxx::ro_string& ns,
                       const ::xsde::cxx::ro_string& n)
  {
    ::xsde::cxx::parser::context& ctx = this->_context ();

    v_state_& vs = *static_cast< v_state_* > (this->v_state_stack_.top ());
    v_state_descr_* vd = vs.data + (vs.size - 1);

    if (vd->func == 0 && vd->state == 0)
    {
      typedef ::fhir::DomainResource_pskel base;
      if (base::_start_element_impl (ns, n))
        return true;
      else
        vd->state = 1;
    }

    while (vd->func != 0)
    {
      (this->*vd->func) (vd->state, vd->count, ns, n, true);

      vd = vs.data + (vs.size - 1);

      if (vd->state == ~0UL && !ctx.error_type ())
        vd = vs.data + (--vs.size - 1);
      else
        break;
    }

    if (vd->func == 0)
    {
      if (vd->state != ~0UL)
      {
        unsigned long s = ~0UL;

        if (n == "identifier" &&
            ns == "http://hl7.org/fhir")
          s = 0UL;
        else if (n == "name" &&
                 ns == "http://hl7.org/fhir")
          s = 1UL;
        else if (n == "telecom" &&
                 ns == "http://hl7.org/fhir")
          s = 2UL;
        else if (n == "gender" &&
                 ns == "http://hl7.org/fhir")
          s = 3UL;
        else if (n == "birthDate" &&
                 ns == "http://hl7.org/fhir")
          s = 4UL;
        else if (n == "address" &&
                 ns == "http://hl7.org/fhir")
          s = 5UL;
        else if (n == "photo" &&
                 ns == "http://hl7.org/fhir")
          s = 6UL;
        else if (n == "managingOrganization" &&
                 ns == "http://hl7.org/fhir")
          s = 7UL;
        else if (n == "active" &&
                 ns == "http://hl7.org/fhir")
          s = 8UL;
        else if (n == "link" &&
                 ns == "http://hl7.org/fhir")
          s = 9UL;

        if (s != ~0UL)
        {
          vd->count++;
          vd->state = ~0UL;

          vd = vs.data + vs.size++;
          vd->func = &Person_pskel::sequence_0;
          vd->state = s;
          vd->count = 0;

          this->sequence_0 (vd->state, vd->count, ns, n, true);
        }
        else
        {
          return false;
        }
      }
      else
        return false;
    }

    return true;
  }

  bool Person_pskel::
  _end_element_impl (const ::xsde::cxx::ro_string& ns,
                     const ::xsde::cxx::ro_string& n)
  {
    v_state_& vs = *static_cast< v_state_* > (this->v_state_stack_.top ());
    v_state_descr_& vd = vs.data[vs.size - 1];

    if (vd.func == 0 && vd.state == 0)
    {
      typedef ::fhir::DomainResource_pskel base;
      if (!base::_end_element_impl (ns, n))
        assert (false);
      return true;
    }

    assert (vd.func != 0);
    (this->*vd.func) (vd.state, vd.count, ns, n, false);

    if (vd.state == ~0UL)
      vs.size--;

    return true;
  }

  void Person_pskel::
  _pre_e_validate ()
  {
    this->v_state_stack_.push ();
    static_cast< v_state_* > (this->v_state_stack_.top ())->size = 0;

    v_state_& vs = *static_cast< v_state_* > (this->v_state_stack_.top ());
    v_state_descr_& vd = vs.data[vs.size++];

    vd.func = 0;
    vd.state = 0;
    vd.count = 0;
    typedef ::fhir::DomainResource_pskel base;
    base::_pre_e_validate ();
  }

  void Person_pskel::
  _post_e_validate ()
  {
    ::xsde::cxx::parser::context& ctx = this->_context ();

    typedef ::fhir::DomainResource_pskel base;
    base::_post_e_validate ();

    if (ctx.error_type ())
      return;

    v_state_& vs = *static_cast< v_state_* > (this->v_state_stack_.top ());
    v_state_descr_* vd = vs.data + (vs.size - 1);

    ::xsde::cxx::ro_string empty;
    while (vd->func != 0)
    {
      (this->*vd->func) (vd->state, vd->count, empty, empty, true);

      if (ctx.error_type ())
        return;

      assert (vd->state == ~0UL);
      vd = vs.data + (--vs.size - 1);
    }


    this->v_state_stack_.pop ();
  }

  void Person_pskel::
  sequence_0 (unsigned long& state,
              unsigned long& count,
              const ::xsde::cxx::ro_string& ns,
              const ::xsde::cxx::ro_string& n,
              bool start)
  {
    ::xsde::cxx::parser::context& ctx = this->_context ();

    XSDE_UNUSED (ctx);

    switch (state)
    {
      case 0UL:
      {
        if (n == "identifier" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->identifier_parser_)
            {
              this->identifier_parser_->pre ();
              ctx.nested_parser (this->identifier_parser_);
            }
          }
          else
          {
            if (this->identifier_parser_ != 0)
            {
              this->identifier_parser_->post_Identifier ();
              this->identifier ();
            }

            count++;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = 1UL;
          // Fall through.
        }
      }
      case 1UL:
      {
        if (n == "name" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->name_parser_)
            {
              this->name_parser_->pre ();
              ctx.nested_parser (this->name_parser_);
            }
          }
          else
          {
            if (this->name_parser_ != 0)
            {
              this->name_parser_->post_HumanName ();
              this->name ();
            }

            count++;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = 2UL;
          // Fall through.
        }
      }
      case 2UL:
      {
        if (n == "telecom" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->telecom_parser_)
            {
              this->telecom_parser_->pre ();
              ctx.nested_parser (this->telecom_parser_);
            }
          }
          else
          {
            if (this->telecom_parser_ != 0)
            {
              this->telecom_parser_->post_ContactPoint ();
              this->telecom ();
            }

            count++;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = 3UL;
          // Fall through.
        }
      }
      case 3UL:
      {
        if (n == "gender" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->gender_parser_)
            {
              this->gender_parser_->pre ();
              ctx.nested_parser (this->gender_parser_);
            }
          }
          else
          {
            if (this->gender_parser_ != 0)
            {
              this->gender_parser_->post_AdministrativeGender ();
              this->gender ();
            }

            count = 0;
            state = 4UL;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = 4UL;
          // Fall through.
        }
      }
      case 4UL:
      {
        if (n == "birthDate" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->birthDate_parser_)
            {
              this->birthDate_parser_->pre ();
              ctx.nested_parser (this->birthDate_parser_);
            }
          }
          else
          {
            if (this->birthDate_parser_ != 0)
            {
              this->birthDate_parser_->post_date ();
              this->birthDate ();
            }

            count = 0;
            state = 5UL;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = 5UL;
          // Fall through.
        }
      }
      case 5UL:
      {
        if (n == "address" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->address_parser_)
            {
              this->address_parser_->pre ();
              ctx.nested_parser (this->address_parser_);
            }
          }
          else
          {
            if (this->address_parser_ != 0)
            {
              this->address_parser_->post_Address ();
              this->address ();
            }

            count++;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = 6UL;
          // Fall through.
        }
      }
      case 6UL:
      {
        if (n == "photo" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->photo_parser_)
            {
              this->photo_parser_->pre ();
              ctx.nested_parser (this->photo_parser_);
            }
          }
          else
          {
            if (this->photo_parser_ != 0)
            {
              this->photo_parser_->post_Attachment ();
              this->photo ();
            }

            count = 0;
            state = 7UL;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = 7UL;
          // Fall through.
        }
      }
      case 7UL:
      {
        if (n == "managingOrganization" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->managingOrganization_parser_)
            {
              this->managingOrganization_parser_->pre ();
              ctx.nested_parser (this->managingOrganization_parser_);
            }
          }
          else
          {
            if (this->managingOrganization_parser_ != 0)
            {
              this->managingOrganization_parser_->post_Reference ();
              this->managingOrganization ();
            }

            count = 0;
            state = 8UL;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = 8UL;
          // Fall through.
        }
      }
      case 8UL:
      {
        if (n == "active" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->active_parser_)
            {
              this->active_parser_->pre ();
              ctx.nested_parser (this->active_parser_);
            }
          }
          else
          {
            if (this->active_parser_ != 0)
            {
              this->active_parser_->post_boolean ();
              this->active ();
            }

            count = 0;
            state = 9UL;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = 9UL;
          // Fall through.
        }
      }
      case 9UL:
      {
        if (n == "link" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->link_parser_)
            {
              this->link_parser_->pre ();
              ctx.nested_parser (this->link_parser_);
            }
          }
          else
          {
            if (this->link_parser_ != 0)
            {
              this->link_parser_->post_Person_Link ();
              this->link ();
            }

            count++;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = ~0UL;
          // Fall through.
        }
      }
      case ~0UL:
        break;
    }
  }

  // Element validation and dispatch functions for Person_Link_pskel.
  //
  bool Person_Link_pskel::
  _start_element_impl (const ::xsde::cxx::ro_string& ns,
                       const ::xsde::cxx::ro_string& n)
  {
    ::xsde::cxx::parser::context& ctx = this->_context ();

    v_state_& vs = *static_cast< v_state_* > (this->v_state_stack_.top ());
    v_state_descr_* vd = vs.data + (vs.size - 1);

    if (vd->func == 0 && vd->state == 0)
    {
      typedef ::fhir::BackboneElement_pskel base;
      if (base::_start_element_impl (ns, n))
        return true;
      else
        vd->state = 1;
    }

    while (vd->func != 0)
    {
      (this->*vd->func) (vd->state, vd->count, ns, n, true);

      vd = vs.data + (vs.size - 1);

      if (vd->state == ~0UL && !ctx.error_type ())
        vd = vs.data + (--vs.size - 1);
      else
        break;
    }

    if (vd->func == 0)
    {
      if (vd->state != ~0UL)
      {
        unsigned long s = ~0UL;

        if (n == "target" &&
            ns == "http://hl7.org/fhir")
          s = 0UL;

        if (s != ~0UL)
        {
          vd->count++;
          vd->state = ~0UL;

          vd = vs.data + vs.size++;
          vd->func = &Person_Link_pskel::sequence_0;
          vd->state = s;
          vd->count = 0;

          this->sequence_0 (vd->state, vd->count, ns, n, true);
        }
        else
        {
          if (vd->count < 1UL)
          {
            this->_schema_error (::xsde::cxx::schema_error::expected_element);
            return true;
          }

          return false;
        }
      }
      else
        return false;
    }

    return true;
  }

  bool Person_Link_pskel::
  _end_element_impl (const ::xsde::cxx::ro_string& ns,
                     const ::xsde::cxx::ro_string& n)
  {
    v_state_& vs = *static_cast< v_state_* > (this->v_state_stack_.top ());
    v_state_descr_& vd = vs.data[vs.size - 1];

    if (vd.func == 0 && vd.state == 0)
    {
      typedef ::fhir::BackboneElement_pskel base;
      if (!base::_end_element_impl (ns, n))
        assert (false);
      return true;
    }

    assert (vd.func != 0);
    (this->*vd.func) (vd.state, vd.count, ns, n, false);

    if (vd.state == ~0UL)
      vs.size--;

    return true;
  }

  void Person_Link_pskel::
  _pre_e_validate ()
  {
    this->v_state_stack_.push ();
    static_cast< v_state_* > (this->v_state_stack_.top ())->size = 0;

    v_state_& vs = *static_cast< v_state_* > (this->v_state_stack_.top ());
    v_state_descr_& vd = vs.data[vs.size++];

    vd.func = 0;
    vd.state = 0;
    vd.count = 0;
    typedef ::fhir::BackboneElement_pskel base;
    base::_pre_e_validate ();
  }

  void Person_Link_pskel::
  _post_e_validate ()
  {
    ::xsde::cxx::parser::context& ctx = this->_context ();

    typedef ::fhir::BackboneElement_pskel base;
    base::_post_e_validate ();

    if (ctx.error_type ())
      return;

    v_state_& vs = *static_cast< v_state_* > (this->v_state_stack_.top ());
    v_state_descr_* vd = vs.data + (vs.size - 1);

    ::xsde::cxx::ro_string empty;
    while (vd->func != 0)
    {
      (this->*vd->func) (vd->state, vd->count, empty, empty, true);

      if (ctx.error_type ())
        return;

      assert (vd->state == ~0UL);
      vd = vs.data + (--vs.size - 1);
    }

    if (vd->count < 1UL)
      this->_schema_error (::xsde::cxx::schema_error::expected_element);

    this->v_state_stack_.pop ();
  }

  void Person_Link_pskel::
  sequence_0 (unsigned long& state,
              unsigned long& count,
              const ::xsde::cxx::ro_string& ns,
              const ::xsde::cxx::ro_string& n,
              bool start)
  {
    ::xsde::cxx::parser::context& ctx = this->_context ();

    XSDE_UNUSED (ctx);

    switch (state)
    {
      case 0UL:
      {
        if (n == "target" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->target_parser_)
            {
              this->target_parser_->pre ();
              ctx.nested_parser (this->target_parser_);
            }
          }
          else
          {
            if (this->target_parser_ != 0)
            {
              this->target_parser_->post_Reference ();
              this->target ();
            }

            count = 0;
            state = 1UL;
          }

          break;
        }
        else
        {
          assert (start);
          if (count < 1UL)
          {
            this->_schema_error (::xsde::cxx::schema_error::expected_element);
            break;
          }

          count = 0;
          state = 1UL;
          // Fall through.
        }
      }
      case 1UL:
      {
        if (n == "assurance" &&
            ns == "http://hl7.org/fhir")
        {
          if (start)
          {
            if (this->assurance_parser_)
            {
              this->assurance_parser_->pre ();
              ctx.nested_parser (this->assurance_parser_);
            }
          }
          else
          {
            if (this->assurance_parser_ != 0)
            {
              this->assurance_parser_->post_IdentityAssuranceLevel ();
              this->assurance ();
            }

            count = 0;
            state = ~0UL;
          }

          break;
        }
        else
        {
          assert (start);
          count = 0;
          state = ~0UL;
          // Fall through.
        }
      }
      case ~0UL:
        break;
    }
  }
}

namespace fhir
{
  // Attribute validation and dispatch functions for IdentityAssuranceLevel_pskel.
  //
  bool IdentityAssuranceLevel_pskel::
  _attribute_impl_phase_one (const ::xsde::cxx::ro_string& ns,
                             const ::xsde::cxx::ro_string& n,
                             const ::xsde::cxx::ro_string& s)
  {
    ::xsde::cxx::parser::context& ctx = this->_context ();

    if (n == "value" && ns.empty ())
    {
      if (this->value_parser_)
      {
        this->value_parser_->pre ();

        this->value_parser_->_pre_impl (ctx);

        if (!ctx.error_type ())
          this->value_parser_->_characters (s);

        if (!ctx.error_type ())
          this->value_parser_->_post_impl ();

        if (!ctx.error_type ())
          this->value_parser_->post_IdentityAssuranceLevel_list ();

        this->value ();
      }

      return true;
    }

    typedef ::fhir::Element_pskel base;
    return base::_attribute_impl_phase_one (ns, n, s);
  }
}

namespace fhir
{
}

#include <xsde/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

